/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "tremuluxGUI.h"

//==============================================================================
NewProjectAudioProcessorEditor::NewProjectAudioProcessorEditor (TremuluxCore& p)
    : AudioProcessorEditor (&p), core (p)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    gui = new TremuluxGUI(&core);
    core.setGUI(gui);
    setSize(WINDOW_W, WINDOW_H);
    addAndMakeVisible(gui);
}

NewProjectAudioProcessorEditor::~NewProjectAudioProcessorEditor()
{
    core.setGUI(nullptr);
    delete gui;
}

//==============================================================================
void NewProjectAudioProcessorEditor::paint (Graphics& g)
{
//    g.fillAll (Colours::white);
//
//    g.setColour (Colours::black);
//    g.setFont (15.0f);
//    g.drawFittedText ("Hello World!", getLocalBounds(), Justification::centred, 1);
}

void NewProjectAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
}
